server {
    listen 8080;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Redireciona todas as rotas para o index.html (SPA)
        try_files $uri $uri/ /index.html;
    }
}
