export const COLLECTIONS = {
  briefings: 'briefings',
  campaigns: 'campaigns',
  cellReports: 'cell_reports',
  cells: 'cells',
  courses: 'courses',
  enrollments: 'enrollments',
  eventEnrollments: 'event_enrollments',
  events: 'events',
  financialReports: 'financial_reports',
  kpiEntries: 'kpi_entries',
  kpiTargets: 'kpi_targets',
  learningAccess: 'learning_access',
  lessons: 'lessons',
  members: 'members',
  ministries: 'ministries',
  ministryEvents: 'ministry_events',
  modules: 'modules',
  orders: 'orders',
  pastoralAppointments: 'pastoral_appointments',
  pastors: 'pastors',
  paymentEvents: 'payment_events',
  paths: 'paths',
  plans: 'plans',
  prayerRequests: 'prayer_requests',
  products: 'products',
  riskAlerts: 'risk_alerts',
  scales: 'scales',
  serviceReports: 'service_reports',
  socialAppointments: 'social_appointments',
  socialProfessionals: 'social_professionals',
  subscriptions: 'subscriptions',
  strategicGoals: 'strategic_goals',
  taskUpdates: 'task_updates',
  tasks: 'tasks',
  transactions: 'transactions',
  units: 'units',
  users: 'users',
  visitorLeads: 'visitor_leads',
} as const;

export type CollectionKey = keyof typeof COLLECTIONS;
export type CollectionName = typeof COLLECTIONS[CollectionKey];
